### ISSUE TITLE
Compile a ES6 version to let it run on non-typescript environment

### ISSUE THREAD

**Issue by CyrusNG** [herberttn/bytenode-webpack-plugin#6]
Hello, May I know whether it can compile a ES6 version to let this run on a environment without typescript support?
current version must have typescript support, otherwise it will error as follow:

`/Users/Cyrus/projectX/node_modules/@herberttn/bytenode-webpack-plugin/lib/index.js:65
                const files = entryPoint?.getFiles() ?? [];
                                         ^

SyntaxError: Unexpected token .
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/Users/Cyrus/projectX/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/Cyrus/projectX/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/Users/Cyrus/projectX/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/Cyrus/projectX/webpack.app.config.js:4:31)
    at Module._compile (/Users/Cyrus/projectX/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/Users/Cyrus/projectX/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/Cyrus/projectX/bin/build.js:3:17)
    at Module._compile (/Users/Cyrus/projectX/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/Users/Cyrus/projectX/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/Cyrus/projectX/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/Users/Cyrus/projectX/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /Users/Cyrus/projectX/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/Cyrus/projectX/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projectX@1.0.0 build: `webpack --progress --profile --bail --mode production --config bin/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the projectX@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Cyrus/.npm/_logs/2021-06-05T04_49_18_584Z-debug.log
The terminal process "/bin/zsh '-c', 'npm run build'" terminated with exit code: 1.`

**Comment by piranna** [comment]
Best practices dictates that `prepare` script should be used, so only transpiled code is published in npm.

**Comment by herberttn** [comment]
@CyrusNG hello!

This already publishes ES6 code and it does not require TypeScript to run.

The problem you're having is that your Node version does not support optional chaining, which was introduced in Node v14.
