### ISSUE TITLE
error on brand new electron app generated with electron-forge

### ISSUE THREAD

**Issue by MetaiR** [herberttn/bytenode-webpack-plugin#8]
hi, I generate an electron application using create-electron-app with electron-forge v6.61 beta channel and when I am trying to run `yarn package` it gives me:
```
An unhandled error has occurred inside Forge:
The "path" argument must be of type string. Received an instance of Object
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:124:11)
    at Object.isAbsolute (path.js:353:5)
    at isDependency (F:\git\electron-test-app\node_modules\@herberttn\bytenode-webpack-plugin\src\index.ts:317:14)
    at F:\git\electron-test-app\node_modules\@herberttn\bytenode-webpack-plugin\src\index.ts:276:24
    at Array.map (<anonymous>)
    at prepare (F:\git\electron-test-app\node_modules\@herberttn\bytenode-webpack-plugin\src\index.ts:275:35)
    at F:\git\electron-test-app\node_modules\@herberttn\bytenode-webpack-plugin\src\index.ts:206:21
    at Array.map (<anonymous>)
    at BytenodeWebpackPlugin.preprocessEntry (F:\git\electron-test-app\node_modules\@herberttn\bytenode-webpack-plugin\src\index.ts:205:20)
    at BytenodeWebpackPlugin.processOptions (F:\git\electron-test-app\node_modules\@herberttn\bytenode-webpack-plugin\src\index.ts:135:52)
    at BytenodeWebpackPlugin.apply (F:\git\electron-test-app\node_modules\@herberttn\bytenode-webpack-plugin\src\index.ts:47:77)
    at createCompiler (F:\git\electron-test-app\node_modules\webpack\lib\webpack.js:74:12)
    at create (F:\git\electron-test-app\node_modules\webpack\lib\webpack.js:127:16)
    at webpack (F:\git\electron-test-app\node_modules\webpack\lib\webpack.js:151:32)
    at f (F:\git\electron-test-app\node_modules\webpack\lib\index.js:55:16)
    at F:\git\electron-test-app\node_modules\@electron-forge\plugin-webpack\src\WebpackPlugin.ts:111:5
error Command failed with exit code 1.
```
what is wrong?

**Comment by MetaiR** [comment]
I downgrade webpack version to 6.54 and everything works ok
